### ISSUE TITLE
OSError: [WinError 126]

### ISSUE THREAD

**Issue by wmeinolf** [AfriGIS-South-Africa/disconnected-islands#11]
Since last QGIS Upgrade to 3.14.15 the plugin can't be installed anymore but creates python error. Unfortunately im on German UI The first lines read: 

Could not load 'disconnected-islands' due to error at call of classfactory() method
OSError [WinError 126] Modul not found
Traceback.....

Konnte Erweiterung 'disconnected-islands' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden 
Traceback (most recent call last):
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\disconnected-islands\__init__.py", line 35, in classFactory
    return DisconnectedIslands(iface)
  File "C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\disconnected-islands\disconnected_islands.py", line 87, in __init__
    self.checkNetworkXModule()
  File "C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\disconnected-islands\disconnected_islands.py", line 229, in checkNetworkXModule
    import networkx
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\networkx\__init__.py", line 114, in 
    import networkx.generators
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\networkx\generators\__init__.py", line 13, in 
    from networkx.generators.geometric import *
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\networkx\generators\geometric.py", line 25, in 
    from scipy.spatial import cKDTree as KDTree
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\scipy\__init__.py", line 136, in 
    from . import _distributor_init
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\scipy\_distributor_init.py", line 61, in 
    WinDLL(os.path.abspath(filename))
  File "C:\OSGeo4W64\apps\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.14.15-Pi Pi, d5114d2cfa 

Python-Pfad:
C:/OSGeo4W64/apps/qgis/./python
C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W64/apps/qgis/./python/plugins
C:\OSGeo4W64\apps\Python37
C:\OSGeo4W64\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGeo4W64\apps\Python37\DLLs
C:\OSGeo4W64\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGeo4W64\apps\Python37\lib\site-packages
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
C:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\WMeinolf\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\WMeinolf\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by wmeinolf** [comment]
Dear @petersmythe, sorry for adressing you directly, however I suspect, the reported issue might be caused by a wrong path on my pc. As all other plugins load I would appreciate a hint, where else I can search for any missing module or wrong path. Thanks a lot and best regards for Germany.

**Comment by wmeinolf** [comment]
Ok, after days of investigation w/o real progress I decided to move from Win10 onto my virtual UBUNTU Machine and install QGIS incl. all plugins from scratch. Ubuntu QGIS did load disconnected-Islands plugin w/o any issue. However on first use I got the message 

2020-08-31T14:22:01     CRITICAL    Error : Exception caught: AttributeError("module 'networkx' has no attribute 'connected_component_subgraphs'"). Please report an issue to the author of the plugin.

Obviously networkx depreciated the attribute a while ago and it was finally removed in version 2.4. 
Wit Infomations form here: https://networkx.github.io/documentation/networkx-2.1/reference/algorithms/generated/networkx.algorithms.components.connected_component_subgraphs.html and here: https://stackoverflow.com/questions/61154740/attributeerror-module-networkx-has-no-attribute-connected-component-subgraph I was finally able to modify disconnected_islands.py, line 317, as follows:

Old:  connected_components = list(nx.connected_component_subgraphs(G))   
New: connected_components = list(G.subgraph(c) for c in nx.connected_components(G))

Now it works fine under UBUNTU, I can use this as workaround. I applied the same under WIN10 environment. Unfortunately it did not help. 

another source recommends to downgrade networksx to v2.3 as workaround.

Thanks again for your support. I hope my findings do help.

**Comment by wmeinolf** [comment]
Ok, I found, the OSError seems to be caused by a bug in latest scipy. Workaround is, to downgrade to scipy version 1.4.1.

I therefore close this case.
